# Generated by Django 4.1.5 on 2023-01-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Art',
        ),
    ]
