# Generated by Django 4.1.6 on 2023-02-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_journal_therapy_delete_art'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapy',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='therapy',
            old_name='bio',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='therapy',
            old_name='name',
            new_name='type',
        ),
    ]
